name: C2ME Build Script

on:
  push:
    branches: [ ver/1.16.5 ]
  pull_request:
    branches: [ ver/1.16.5 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Pull Gradle Cache
      uses: actions/cache@v2
      id: gradle-cache
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-maven-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-java-11
        
    - name: Build C2ME
      run: |
        ./gradlew clean build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: C2ME
        path: ./build/libs/C2ME-fabric-0.1-SNAPSHOT-all.jar
      
